### ISSUE TITLE
Code in app/src/main/java/seedu/address

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103-T14-3/main#45]
Guys, look like you have some code in a folder `app/src/main/java/seedu/address`
is this some temp code to be removed later?

Note that our code analysis scripts expects to find all source code inside the [root]/src/ folder.

**Comment by Oscar-B-Liang** [comment]
Yes professor, we still keep the original code in case we want to visit them as reference. They will be removed finally.

**Comment by damithc** [comment]
Understood. By the way, with Git, there is no need to keep such copies as you can always refer back to any previous state of the code.
